# Generated by Django 5.1.3 on 2024-12-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=250)),
                ('pais', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=900)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
